name : checking Github Actions 
on : 
 push:
  branches : [main] 
jobs:
 build:
  runs-on : ubuntu:latest
  steps : 
  - name : Running Python Test 
  - uses : actions/checkout@v3
  - name : Setup Python 
    uses : actions/setup-python@v4
    with : 
     python-version : 3.10
  - name : Running test 
  - run : pip install -r requirements.txt 
  - name : Testing Now 
  - run : pytest simple.py 
  
    
    
   
  
 
 


